upstream frontend {
    server frontend:3000;
}

upstream chat-backend {
    server virtual-assistant:5000;
}

server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /chat {
        proxy_pass http://chat-backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}